# Generated by Django 6.0.5 on 2026-06-26 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500, verbose_name='Descripción del Pedido/Productos')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Total')),
                ('status', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado'), ('Enviado', 'Enviado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=20, verbose_name='Estado del Pedido')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.record', verbose_name='Cliente')),
            ],
        ),
    ]
