# Generated by Django 6.0.5 on 2026-06-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_order_channel_order_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
