# Generated by ChatGPT on 2026-06-26

from django.db import migrations, models


def move_product_images_to_static(apps, schema_editor):
    Product = apps.get_model('website', 'Product')
    local_images = {
        'Camiseta Oversize Negra': 'img/products/camiseta-oversize-negra.svg',
        'Jeans Slim Azul': 'img/products/jeans-slim-azul.svg',
        'Chaqueta Denim': 'img/products/chaqueta-denim.svg',
        'Hoodie Gris': 'img/products/hoodie-gris.svg',
        'Tenis Blancos Urban': 'img/products/tenis-blancos-urban.svg',
        'Manzana Roja': 'img/products/camiseta-oversize-negra.svg',
        'Banano': 'img/products/jeans-slim-azul.svg',
        'Naranja': 'img/products/chaqueta-denim.svg',
        'Fresa': 'img/products/hoodie-gris.svg',
        'Piña': 'img/products/tenis-blancos-urban.svg',
    }

    for product in Product.objects.all():
        if product.image_url.startswith('img/products/'):
            continue
        new_path = local_images.get(product.name)
        if new_path:
            product.image_url = new_path
            product.save(update_fields=['image_url'])


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_product_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.RunPython(move_product_images_to_static, migrations.RunPython.noop),
    ]
