# Generated by ChatGPT on 2026-06-26

from pathlib import Path
import shutil

from django.conf import settings
from django.db import migrations, models


def copy_existing_product_images(apps, schema_editor):
    Product = apps.get_model('website', 'Product')
    source_dir = Path(settings.BASE_DIR) / 'website' / 'templates' / 'static' / 'img' / 'products'
    media_dir = Path(settings.MEDIA_ROOT) / 'products'
    media_dir.mkdir(parents=True, exist_ok=True)

    legacy_name_map = {
        'Camiseta Oversize Negra': 'camiseta-oversize-negra.svg',
        'Jeans Slim Azul': 'jeans-slim-azul.svg',
        'Chaqueta Denim': 'chaqueta-denim.svg',
        'Hoodie Gris': 'hoodie-gris.svg',
        'Tenis Blancos Urban': 'tenis-blancos-urban.svg',
        'Manzana Roja': 'camiseta-oversize-negra.svg',
        'Banano': 'jeans-slim-azul.svg',
        'Naranja': 'chaqueta-denim.svg',
        'Fresa': 'hoodie-gris.svg',
        'Piña': 'tenis-blancos-urban.svg',
    }

    for product in Product.objects.all():
        current_value = str(product.image_url or '').strip()
        filename = ''

        if current_value.startswith('products/'):
            filename = current_value.split('/', 1)[1]
        elif current_value.startswith('img/products/'):
            filename = current_value.split('/', 2)[2]
        elif current_value:
            filename = legacy_name_map.get(product.name, '')

        if not filename:
            continue

        source_file = source_dir / filename
        target_file = media_dir / filename
        if source_file.exists() and not target_file.exists():
            shutil.copy2(source_file, target_file)

        product.image_url = f'products/{filename}'
        product.save(update_fields=['image_url'])


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_product_image_url_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.RunPython(copy_existing_product_images, migrations.RunPython.noop),
    ]
